const mockRestaurants = [
  {
    id: '101',
    name: 'Gourmet Bistro',
    address: '12 Market St, Downtown',
    imageURL: 'https://placehold.co/1200x800/111827/ffffff?text=Gourmet+Bistro',
    rating: 4.6,
    cuisine: 'Continental',
  },
  {
    id: '102',
    name: 'Sunset Grill',
    address: '98 Ocean Ave',
    imageURL: 'https://placehold.co/1200x800/0f172a/ffffff?text=Sunset+Grill',
    rating: 4.3,
    cuisine: 'Grill, Seafood',
  },
  {
    id: '103',
    name: 'Spice Route',
    address: '7 Spice Lane',
    imageURL: 'https://placehold.co/1200x800/1f2937/ffffff?text=Spice+Route',
    rating: 4.7,
    cuisine: 'Indian',
  },
  {
    id: '104',
    name: 'Olive Garden-ish',
    address: '22 Olive Rd',
    imageURL:
      'https://placehold.co/1200x800/0b1220/ffffff?text=Olive+Garden-ish',
    rating: 4.2,
    cuisine: 'Italian',
  },
  {
    id: '105',
    name: 'The Pancake House',
    address: '3 Morning Blvd',
    imageURL: 'https://placehold.co/1200x800/111827/ffffff?text=Pancake+House',
    rating: 4.4,
    cuisine: 'Breakfast, Cafe',
  },
  {
    id: '106',
    name: 'Sushi Station',
    address: '7 Harbor St',
    imageURL: 'https://placehold.co/1200x800/022c4a/ffffff?text=Sushi+Station',
    rating: 4.5,
    cuisine: 'Japanese',
  },
  {
    id: '107',
    name: 'Urban Taco',
    address: '45 Central Plaza',
    imageURL: 'https://placehold.co/1200x800/4a044e/ffffff?text=Urban+Taco',
    rating: 4.3,
    cuisine: 'Mexican',
  },
  {
    id: '108',
    name: 'Burger Bay',
    address: '77 Seaside Ave',
    imageURL: 'https://placehold.co/1200x800/2a2e32/ffffff?text=Burger+Bay',
    rating: 4.1,
    cuisine: 'American, Fast Food',
  },
  {
    id: '109',
    name: 'Royal Curry House',
    address: '12 Prince Rd',
    imageURL:
      'https://placehold.co/1200x800/4b5563/ffffff?text=Royal+Curry+House',
    rating: 4.8,
    cuisine: 'Indian, Mughlai',
  },
  {
    id: '110',
    name: 'Noodle Nook',
    address: '19 Asia St',
    imageURL: 'https://placehold.co/1200x800/0f172a/ffffff?text=Noodle+Nook',
    rating: 4.5,
    cuisine: 'Chinese, Thai',
  },
  {
    id: '111',
    name: 'BBQ Nation',
    address: '34 Flame Rd',
    imageURL: 'https://placehold.co/1200x800/7f1d1d/ffffff?text=BBQ+Nation',
    rating: 4.6,
    cuisine: 'Grill, Barbecue',
  },
  {
    id: '112',
    name: 'Pizza Factory',
    address: '9 Dough Street',
    imageURL: 'https://placehold.co/1200x800/78350f/ffffff?text=Pizza+Factory',
    rating: 4.4,
    cuisine: 'Italian, Pizza',
  },
  {
    id: '113',
    name: 'Veggie Delight',
    address: '88 Garden Road',
    imageURL: 'https://placehold.co/1200x800/166534/ffffff?text=Veggie+Delight',
    rating: 4.3,
    cuisine: 'Vegan, Organic',
  },
  {
    id: '114',
    name: 'The Steak House',
    address: '10 Prime Ave',
    imageURL:
      'https://placehold.co/1200x800/451a03/ffffff?text=The+Steak+House',
    rating: 4.7,
    cuisine: 'Steak, American',
  },
  {
    id: '115',
    name: 'Café Mocha',
    address: '3 Bean Street',
    imageURL: 'https://placehold.co/1200x800/422006/ffffff?text=Cafe+Mocha',
    rating: 4.5,
    cuisine: 'Cafe, Desserts',
  },
  {
    id: '116',
    name: 'Dragon Wok',
    address: '66 Lantern Ave',
    imageURL: 'https://placehold.co/1200x800/0f172a/ffffff?text=Dragon+Wok',
    rating: 4.4,
    cuisine: 'Asian Fusion',
  },
  {
    id: '117',
    name: 'Tandoori Nights',
    address: '31 Spice Blvd',
    imageURL:
      'https://placehold.co/1200x800/450a0a/ffffff?text=Tandoori+Nights',
    rating: 4.6,
    cuisine: 'Indian, Punjabi',
  },
  {
    id: '118',
    name: 'Greek Treat',
    address: '5 Olive Lane',
    imageURL: 'https://placehold.co/1200x800/1e3a8a/ffffff?text=Greek+Treat',
    rating: 4.2,
    cuisine: 'Mediterranean, Greek',
  },
  {
    id: '119',
    name: 'Crust & Crumb',
    address: '27 Baker St',
    imageURL:
      'https://placehold.co/1200x800/2b2f3a/ffffff?text=Crust+%26+Crumb',
    rating: 4.5,
    cuisine: 'Bakery, Cafe',
  },
  {
    id: '120',
    name: 'Tempura Town',
    address: '18 Tokyo Blvd',
    imageURL: 'https://placehold.co/1200x800/1e293b/ffffff?text=Tempura+Town',
    rating: 4.3,
    cuisine: 'Japanese, Seafood',
  },
  {
    id: '121',
    name: 'Farm Fresh Diner',
    address: '44 Green Valley',
    imageURL:
      'https://placehold.co/1200x800/14532d/ffffff?text=Farm+Fresh+Diner',
    rating: 4.6,
    cuisine: 'Organic, Continental',
  },
  {
    id: '122',
    name: 'Brew & Bite',
    address: '101 Coffee Ave',
    imageURL: 'https://placehold.co/1200x800/3b0764/ffffff?text=Brew+%26+Bite',
    rating: 4.5,
    cuisine: 'Cafe, Snacks',
  },
  {
    id: '123',
    name: 'Curry Leaf',
    address: '55 Heritage Street',
    imageURL: 'https://placehold.co/1200x800/713f12/ffffff?text=Curry+Leaf',
    rating: 4.7,
    cuisine: 'South Indian',
  },
  {
    id: '124',
    name: 'The Pasta Bar',
    address: '42 Milan Ave',
    imageURL: 'https://placehold.co/1200x800/312e81/ffffff?text=The+Pasta+Bar',
    rating: 4.4,
    cuisine: 'Italian',
  },
  {
    id: '125',
    name: 'Falafel Street',
    address: '73 Mid East Rd',
    imageURL: 'https://placehold.co/1200x800/3f3f46/ffffff?text=Falafel+Street',
    rating: 4.5,
    cuisine: 'Middle Eastern',
  },
]

export default mockRestaurants
